

---
version: 1.0.0
recipes:
- link: recipes/Recipe-1.md
  title: Card Transaction Enrichment
  type: recipe
- link: recipes/Recipe-2.md
  title: Account Transaction Enrichment
  type: recipe
- link: recipes/Recipe-3.md
  title: ATM Transaction Enrichment
  type: recipe
- link: recipes/Recipe-4.md
  title: BillPay Transaction Enrichment
  type: recipe
