################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Integrated Transaction Enrichment
  productionDescription: A cloud-based service to cleanse and then enrich transactions with additional data attributes, including merchant names, location, merchant logos, categories, transaction type and merchant contact information.
  whoIsItFor: Financial Institutions, fintech solution providers, and anyone else who want to cleanse and enrich the transactions.
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Fiserv logo™
benefits:
  - title: Reduce customer service calls
    description:  Reduce customer service calls due to vague or incorrect transaction information.
  - title: Lower false chargebacks
    description:  Lower false chargebacks that may arise from unrecognizable transactions.
  - title: Increase user satisfaction
    description:  Richer transaction receipts and statements increases customer satisfaction
featuredFeatures:
  - title: Card Transaction Enrichment
    description:  Enrich pending or posted credit or debit card transactions by leveraging real-time authorization attributes not available elsewhere.
    tags: ["real-time", "pending", "card"]  
  - title: BillPay & ACH Transaction Enrichment
    description:  Enrich BillPay or other ACH transactions with consistent merchant name and categories as card transactions.
    tags: ["Category", "BillPay", "ACH"]
  - title: Digital Payment Enrichment
    description:  Enrich Zelle, P2P, and other digital payment transactions with the automatic detection of person's name vs merchant name.
    tags: ["Zelle", "P2P", "Digital"]